export const authComponentAppearance = {
  elements: {
    rootBox: 'mx-auto w-full [&>div]:w-full',
    cardBox: 'mx-auto w-full',
    card: 'w-full rounded-[1.5rem] border border-[rgba(39,50,64,0.88)] bg-[rgba(8,11,17,0.98)] shadow-none',
    headerTitle: 'text-[color:var(--lab-text)]',
    headerSubtitle: 'text-[color:var(--lab-text-muted)]',
    socialButtonsBlockButton: 'border border-[rgba(39,50,64,0.88)] bg-[rgba(19,28,38,0.94)] text-[color:var(--lab-text)] hover:bg-[rgba(26,34,45,1)]',
    socialButtonsBlockButtonText: 'text-[color:var(--lab-text)]',
    formButtonPrimary: 'rounded-full border border-[rgba(228,209,174,0.92)] bg-[color:var(--lab-gold)] text-[#15181e] shadow-none hover:bg-[#eddcbc]',
    formFieldLabel: 'text-[color:var(--lab-text-muted)]',
    formFieldInput: 'rounded-2xl border border-[rgba(39,50,64,0.9)] bg-[rgba(8,11,17,0.96)] text-[color:var(--lab-text)]',
    footerActionText: 'text-[color:var(--lab-text-muted)]',
    footerActionLink: 'text-[color:var(--lab-gold)] hover:text-[color:var(--lab-text)]',
    identityPreviewText: 'text-[color:var(--lab-text)]',
    formResendCodeLink: 'text-[color:var(--lab-gold)] hover:text-[color:var(--lab-text)]',
    otpCodeFieldInput: 'rounded-2xl border border-[rgba(39,50,64,0.9)] bg-[rgba(8,11,17,0.96)] text-[color:var(--lab-text)]',
    alertText: 'text-[#f2b1b1]',
  },
} as const;
